#!/usr/bin/env bash

pushd . 1>/dev/null
cd ~/git/casa
[ -f ~/.bashrc ] && cp ~/.bashrc{,.bak}
cd ~
for s in $(ls -d ~/git/casa/.* | grep -Ev '\.$|\.git')
do
    ln -sf ~/git/casa/$s
done
echo "casa profile installed"
. ~/.bashrc
popd 1>/dev/null
