#!/usr/bin/env bash

pushd . 1>/dev/null
SRCDIR=~/code
cd ${SRCDIR}/casa
[ -f ~/.bashrc ] && cp ~/.bashrc{,.bak}
cd ~
for s in $(ls -d ${SRCDIR}/casa/.* | grep -Ev '\.$|\.git$')
do
    ln -fs ${s}
done
echo "casa profile installed"
. ~/.bashrc
popd 1>/dev/null
